server:
  port: 8082
  servlet:
    context-path: /

spring:
  application:
    name: user-service
  
  # 数据库配置 - 与原系统共享，但使用独立连接池
  datasource:
    url: jdbc:mysql://localhost:3306/moviesystem_db?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&allowMultiQueries=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:your_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 连接池配置
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: UserServiceHikariCP
  
  # MyBatis配置替代JPA，更好地与原系统兼容
  mybatis:
    configuration:
      map-underscore-to-camel-case: true
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    type-aliases-package: com.it.movie.user.entity
  
  # Redis缓存配置
  redis:
    host: localhost
    port: 6379
    timeout: 3000ms
    database: 1  # Session使用数据库1，与原系统共享
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  
  # Session配置 - 跨服务共享
  session:
    store-type: redis
    timeout: 86400  # 24小时
    redis:
      namespace: movie:session

# Eureka客户端配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
    metadata-map:
      version: 1.3.0
      description: 用户管理微服务-并行运行模式

# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

# 监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

# 日志配置
logging:
  level:
    com.it.movie.user: DEBUG
    org.springframework.web: INFO
    org.mybatis: DEBUG
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr([USER-SERVICE]){magenta} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
  file:
    name: logs/user-service.log

# 微服务特定配置
microservice:
  user:
    # 兼容模式：与原系统并行运行
    compatibility-mode: true
    # API路径前缀
    api-prefix: /microservice/api/user
    # 缓存TTL（秒）
    cache-ttl: 300
    # 安全模式：只读数据库访问
    read-only-mode: false